### ISSUE TITLE
Set http(s) proxy and/or no_proxy appropriately in build-image.sh

### ISSUE THREAD

**Issue by pperiyasamy** [intel/network-resources-injector#10]
The build-image.sh sets docker build arguments with http(s) proxy and no proxy though these are not set in a test environment which makes `make image` step fail as part of network-resources-injector installation.

Please set those parameters only if these are defined in system env variables.

**Comment by przemeklal** [comment]
Hi @pperiyasamy, I'm sorry but I couldn't reproduce it, I tried to run `make image` on a system without proxy env variables (no proxy settings in the ~/.docker/config.json either) and it builds just fine. Are you sure that proxy env variables are the root cause here?

**Comment by pperiyasamy** [comment]
Hi @przemeklal Our test setup is running without http proxy, so when i ran `make image` , then http gateway timeout error is seen while downloading docker images. After removing --build-arg parameters in [build-image.sh](https://github.com/intel/network-resources-injector/blob/master/scripts/build-image.sh), then it started working fine.  hence i thought these parameters should be set only when required like [this one](https://github.com/intel/sriov-network-device-plugin/blob/master/Makefile#L27).

**Comment by przemeklal** [comment]
Interesting - I'll look into this, should be easy to fix.
