### ISSUE TITLE
network resources injector cannot handle pods from deployment properly

### ISSUE THREAD

**Issue by zshi-redhat** [intel/network-resources-injector#26]
network resources injector inspects the net-attach-def and injects the sriov resource request to pod resource request/limits. It works perfectly with a pod, but has issues dealing with a deployment pod in a non-default namespace.

The workflow of network resources injector is:
1) watch the creation/update of *pod*
2) receive AdmissionReview request
3) deserialize pod object from AdmissionReview request
4) set pod namespace to 'default', If pod object doesn't contain valid namespace (e.g. empty namespace for a deployment pod)
5) call API to retrieve net-attach-def with above namespace + net-attach-def name (from pod object annotation)
6) If resource is found in net-attach-def, inject the resource name in pod object. else do nothing.

The problem for a deployment pod happens in step 5),  the deserialized deployment pod object contains an empty namespace field, so it is set to default namespace, which in turn cause the actual namespace of deployment not be respected. So when network-resources-injector tries to get the net-attach-def with default namespace, it fails.

It looks like we have two possible ways to fix this:
1) find a way to get pod namespace from deployment
2) watch the creation/update of deployment object and mutate the deployment spec (this implies that we should ignore the pod creation/update event that's from the same deployment)

**Comment by ahalim-intel** [comment]
cc @przemeklal 
PTAL

**Comment by pperiyasamy** [comment]
@zshi-redhat @przemeklal Let me have a look at this issue and propose a fix (with 1st approach).

**Comment by JanScheurich** [comment]
Is it a bug or a feature of K8s that a pod of a deployment does not inherit the namespace of its deployment?

**Comment by pperiyasamy** [comment]
> Is it a bug or a feature of K8s that a pod of a deployment does not inherit the namespace of its deployment?

@JanScheurich AFAIK, the pod replica doesn't have a namespace when its admission review request is received on the webhook, so NRI must rely on the namespace set at the deployment level so that net-attach-def object can be queried from the appropriate namespace. I'm already working on a patch for it. 
But I can see pod replica has namespace set once it is deployed on the node.

**Comment by JanScheurich** [comment]
@pperiyasamy Good to know that the deployment pod eventually inherits the deployment's namespace, but I still consider it strange that the deployment control loop does not set the namespace initially when it creates the pod in the first place, which, I assume, is what triggers the NRI pod admission controller webhook.

**Comment by pperiyasamy** [comment]
> @pperiyasamy Good to know that the deployment pod eventually inherits the deployment's namespace, but I still consider it strange that the deployment control loop does not set the namespace initially when it creates the pod in the first place, which, I assume, is what triggers the NRI pod admission controller webhook.

Yes @JanScheurich ,  you are correct, This seems to be a k8s bug. But anyway I've raised a PR #28 in NRI to solve this. Please have a look.

**Comment by pperiyasamy** [comment]
@zshi-redhat , As PRs #28 and #31 fixe this issue, can we close it ?

**Comment by zshi-redhat** [comment]
> @zshi-redhat , As PRs #28 and #31 fix this issue, can we close it ?

yes.
